name: Build and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/portfolio:latest
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.run_id }}

      - name: Trigger Keel Update
        run: |
          # Sends the specific Run ID tag to Keel's native webhook endpoint
          curl -X POST -H "Content-Type: application/json" \
          -d '{"name": "ghcr.io/${{ github.repository_owner }}/portfolio", "tag": "${{ github.run_id }}"}' \
          https://keel-webhook.thekyle.net/v1/webhooks/native